#:kivy 1.1.0

<GraphBox>:
    canvas:
        Color:
            rgba: 0, 0, 0, 1
        Rectangle:
            pos: self.pos
            size: self.size
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos[0] + self.borderWidth, self.pos[1] + self.borderWidth
            size: self.size[0] - 2 * self.borderWidth, self.size[1] - 2 * self.borderWidth



